---
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
version: "2"

linters:
  default: all

  # explicitly disabled linters
  disable:
    - containedctx    
    - contextcheck
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - exhaustive
    - forbidigo
    - gomodguard # no go.mod at root level    
    - gochecknoglobals  # no configuration options
    - nilnil
    - nlreturn          # redundant with wsl
    - paralleltest
    - revive
    - tagalign
    - thelper
    - varnamelen
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 12

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Close

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-local: true

    gosec:
      excludes:
        - G104  # Errors unhandled
        - G304  # Potential file inclusion via variable (see https://github.com/golang/go/issues/67002)

    ireturn:
      allow:
        - error
        - empty
        - stdlib
        - generic
        - proto.Message
        - v3.ImporterClient

    lll:
      line-length: 150

    recvcheck:
      exclusions:
        - "*.Map"

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports