---
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
version: "2"

linters:
  default: all

  # explicitly disabled linters
  disable:
    - containedctx    
    - contextcheck
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - exhaustive
    - forbidigo
    - gomodguard # no go.mod at root level    
    - gochecknoglobals  # no configuration options
    - nilnil
    - nlreturn          # redundant with wsl
    - paralleltest
    - revive
    - tagalign
    - thelper
    - varnamelen
    - wrapcheck

  settings:
    gomoddirectives:
      replace-local: true
    lll:
      line-length: 140 # a lot of parameter lines over 130 characters
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 80
      ignore-comments: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    cyclop:
      max-complexity: 12    
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped