builds:
  - id: ds-load
    main: ./cli/cmd/ds-load
    binary: ds-load
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds-load/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"


  - id: ds-load-auth0
    main: ./plugins/auth0/cmd/ds-load-auth0
    binary: ds-load-auth0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds-load/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: ds-load-okta
    main: ./plugins/okta/cmd/ds-load-okta
    binary: ds-load-okta
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds-load/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: ds-load-azuread
    main: ./plugins/azuread/cmd/ds-load-azuread
    binary: ds-load-azuread
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds-load/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds-load/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE
      - README.md
    name_template: >-
      ds-load_{{.Version}}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

release:
  github:
    owner: aserto-dev
    name: ds-load

  draft: false
  prerelease: auto
  name_template: "ds-load {{.Tag}}"

brews:
  -
    name: ds-load

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.ASERTO_TAP }}"

    url_template: "https://github.com/aserto-dev/ds-load/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    
    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "DS Load CLI"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/ds-load version"
    install: |
      bin.install "ds-load"
      bin.install "ds-load-auth0"
      bin.install "ds-load-azuread"
      bin.install "ds-load-okta"
