builds:
  - id: ds
    main: ./cli/cmd/ds
    binary: ds
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"


  - id: ds-auth0
    main: ./plugins/auth0/cmd/ds-auth0
    binary: ds-auth0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: ds-okta
    main: ./plugins/okta/cmd/ds-okta
    binary: ds-okta
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/ds/sdk/common/version.ver={{.Version}}
      - -X github.com/aserto-dev/ds/sdk/common/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/ds/sdk/common/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE
      - README.md
    name_template: >-
      ds_load_{{.Version}}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

release:
  github:
    owner: aserto-dev
    name: ds

  draft: false
  prerelease: auto
  name_template: "ds {{.Tag}}"

brews:
  -
    name: ds

    tap:
      owner: aserto-dev
      name: aserto-tap
      token: "{{ .Env.ASERTO_TAP }}"

    url_template: "https://github.com/aserto-dev/ds/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    
    download_strategy: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "DS Load CLI"

    skip_upload: false

    test: |
      system "#{bin}/ds version"
    install: |
      bin.install "ds"
      bin.install "ds-auth0"
      bin.install "ds-okta"
