// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: dsload.proto

package msg

import (
	v2 "github.com/aserto-dev/go-directory/aserto/directory/common/v2"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchType int32

const (
	BatchType_NONE  BatchType = 0
	BatchType_BEGIN BatchType = 1
	BatchType_END   BatchType = 2
)

// Enum value maps for BatchType.
var (
	BatchType_name = map[int32]string{
		0: "NONE",
		1: "BEGIN",
		2: "END",
	}
	BatchType_value = map[string]int32{
		"NONE":  0,
		"BEGIN": 1,
		"END":   2,
	}
)

func (x BatchType) Enum() *BatchType {
	p := new(BatchType)
	*p = x
	return p
}

func (x BatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_dsload_proto_enumTypes[0].Descriptor()
}

func (BatchType) Type() protoreflect.EnumType {
	return &file_dsload_proto_enumTypes[0]
}

func (x BatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchType.Descriptor instead.
func (BatchType) EnumDescriptor() ([]byte, []int) {
	return file_dsload_proto_rawDescGZIP(), []int{0}
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type BatchType `protobuf:"varint,1,opt,name=type,proto3,enum=aserto.dsload.BatchType" json:"type,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dsload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_dsload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_dsload_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetType() BatchType {
	if x != nil {
		return x.Type
	}
	return BatchType_NONE
}

type PluginMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*PluginMessage_Object
	//	*PluginMessage_Relation
	//	*PluginMessage_Batch
	//	*PluginMessage_Error
	Data isPluginMessage_Data `protobuf_oneof:"data"`
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dsload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dsload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_dsload_proto_rawDescGZIP(), []int{1}
}

func (m *PluginMessage) GetData() isPluginMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *PluginMessage) GetObject() *v2.Object {
	if x, ok := x.GetData().(*PluginMessage_Object); ok {
		return x.Object
	}
	return nil
}

func (x *PluginMessage) GetRelation() *v2.Relation {
	if x, ok := x.GetData().(*PluginMessage_Relation); ok {
		return x.Relation
	}
	return nil
}

func (x *PluginMessage) GetBatch() *Batch {
	if x, ok := x.GetData().(*PluginMessage_Batch); ok {
		return x.Batch
	}
	return nil
}

func (x *PluginMessage) GetError() *status.Status {
	if x, ok := x.GetData().(*PluginMessage_Error); ok {
		return x.Error
	}
	return nil
}

type isPluginMessage_Data interface {
	isPluginMessage_Data()
}

type PluginMessage_Object struct {
	Object *v2.Object `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type PluginMessage_Relation struct {
	Relation *v2.Relation `protobuf:"bytes,2,opt,name=relation,proto3,oneof"`
}

type PluginMessage_Batch struct {
	Batch *Batch `protobuf:"bytes,3,opt,name=batch,proto3,oneof"`
}

type PluginMessage_Error struct {
	Error *status.Status `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*PluginMessage_Object) isPluginMessage_Data() {}

func (*PluginMessage_Relation) isPluginMessage_Data() {}

func (*PluginMessage_Batch) isPluginMessage_Data() {}

func (*PluginMessage_Error) isPluginMessage_Data() {}

type Transform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects   []*v2.Object   `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Relations []*v2.Relation `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
}

func (x *Transform) Reset() {
	*x = Transform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dsload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_dsload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_dsload_proto_rawDescGZIP(), []int{2}
}

func (x *Transform) GetObjects() []*v2.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Transform) GetRelations() []*v2.Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

var File_dsload_proto protoreflect.FileDescriptor

var file_dsload_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x64, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x17, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2f, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x35, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2e,
	0x64, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xf3, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x73, 0x65, 0x72, 0x74,
	0x6f, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x42, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x73, 0x65, 0x72, 0x74,
	0x6f, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x73, 0x65, 0x72,
	0x74, 0x6f, 0x2e, 0x64, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48,
	0x00, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8d, 0x01, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x3c, 0x0a, 0x07, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x73,
	0x65, 0x72, 0x74, 0x6f, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x42, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x73,
	0x65, 0x72, 0x74, 0x6f, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x29, 0x0a, 0x09,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x76,
	0x2f, 0x64, 0x73, 0x2d, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x73, 0x67,
	0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dsload_proto_rawDescOnce sync.Once
	file_dsload_proto_rawDescData = file_dsload_proto_rawDesc
)

func file_dsload_proto_rawDescGZIP() []byte {
	file_dsload_proto_rawDescOnce.Do(func() {
		file_dsload_proto_rawDescData = protoimpl.X.CompressGZIP(file_dsload_proto_rawDescData)
	})
	return file_dsload_proto_rawDescData
}

var file_dsload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dsload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dsload_proto_goTypes = []interface{}{
	(BatchType)(0),        // 0: aserto.dsload.BatchType
	(*Batch)(nil),         // 1: aserto.dsload.Batch
	(*PluginMessage)(nil), // 2: aserto.dsload.PluginMessage
	(*Transform)(nil),     // 3: aserto.dsload.Transform
	(*v2.Object)(nil),     // 4: aserto.directory.common.v2.Object
	(*v2.Relation)(nil),   // 5: aserto.directory.common.v2.Relation
	(*status.Status)(nil), // 6: google.rpc.Status
}
var file_dsload_proto_depIdxs = []int32{
	0, // 0: aserto.dsload.Batch.type:type_name -> aserto.dsload.BatchType
	4, // 1: aserto.dsload.PluginMessage.object:type_name -> aserto.directory.common.v2.Object
	5, // 2: aserto.dsload.PluginMessage.relation:type_name -> aserto.directory.common.v2.Relation
	1, // 3: aserto.dsload.PluginMessage.batch:type_name -> aserto.dsload.Batch
	6, // 4: aserto.dsload.PluginMessage.error:type_name -> google.rpc.Status
	4, // 5: aserto.dsload.Transform.objects:type_name -> aserto.directory.common.v2.Object
	5, // 6: aserto.dsload.Transform.relations:type_name -> aserto.directory.common.v2.Relation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_dsload_proto_init() }
func file_dsload_proto_init() {
	if File_dsload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dsload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dsload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dsload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dsload_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PluginMessage_Object)(nil),
		(*PluginMessage_Relation)(nil),
		(*PluginMessage_Batch)(nil),
		(*PluginMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dsload_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dsload_proto_goTypes,
		DependencyIndexes: file_dsload_proto_depIdxs,
		EnumInfos:         file_dsload_proto_enumTypes,
		MessageInfos:      file_dsload_proto_msgTypes,
	}.Build()
	File_dsload_proto = out.File
	file_dsload_proto_rawDesc = nil
	file_dsload_proto_goTypes = nil
	file_dsload_proto_depIdxs = nil
}
